package au.edu.usyd.it.xmlreader;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;


/*
 * extract three fields from .xml generated by shot detection program
 * 
 *  <begin_frame> <key_frame> <end_frame>
 * 
 * and store target values to a txt file
 * 
 * */
public class XMLReader 
{
	static String fileDir = "/Users/natechen/Desktop/20090601_shots/";
	
	public static void main(String[] args)
	{
		File dir = new File(fileDir);
		for(String str : dir.list())
		{
			/*
			 * use ".mp4.xml" for now
			 * */
			if(str.endsWith(".mp4.xml"))
			{
				try
				{
					File file = new File(fileDir + str);
					File output = new File(fileDir + "xmlTOtxt/" + str.replaceAll(".xml", ".txt"));
					if(!output.exists())
					{
						output.createNewFile();
					}
					PrintWriter out = new PrintWriter(output);
					Scanner scn = new Scanner(file);
					String result = "";
					int shotNum = 0;
					while(scn.hasNext())
					{
						String string = scn.nextLine();
						
						/*
						 * total number of shots
						 * 
						 * */
						if(string.contains("<ShotSegment id"))
						{
							String s = string.substring(string.indexOf("\"") + 1, string.lastIndexOf("\""));
							shotNum = Integer.parseInt(s);
						}
						
						/*
						 * shot detection
						 * first frame, last frame and the one in the middle
						 * 
						 * */
						if(string.contains("<begin_frame>") || string.contains("<key_frame>") || string.contains("<end_frame>"))
						{
							String st = string.substring(string.indexOf(">")+1, string.lastIndexOf("<"));
							result = result + st + "\n";
						}
					}
					/*
					 * output the key frames' info
					 * 
					 * */
					if(!result.trim().isEmpty())
					{
						out.println(shotNum + "\n" + result);
					}
					out.close();
				}
				catch(Exception e)
				{
					e.printStackTrace();
				}
			}
		}
	}
}
